/* ═══════════════════════════════════════════════════════════
   RETROVERSE — CANAIS DA RETROTV (fonte única)
   47 canais de TV ao vivo — sintonizou, tem sinal.

   Todos verificados em 16/08/2026: playlist 200 + variante +
   segmento real 200 + CORS * — 3 rodadas com intervalo, 3/3.
   Fonte: base iptv-org + testes próprios.

   tipo: 'iptv' → url = playlist .m3u8
   seguro: true  → https, funciona em qualquer lugar (35 canais)
   seguro: false → http, o navegador BLOQUEIA em página https
                   (mixed content). Funciona ao abrir local:
                   file:// ou http://localhost. A RetroTV marca
                   esses canais na grade e avisa no OSD. (12 canais)
   ═══════════════════════════════════════════════════════════ */
window.RV_CANAIS = [

  /* ── INFANTIL ── */
  { nome: 'DISNEY CHANNEL', programa: 'DESENHOS · 24/7', categoria: 'INFANTIL', cor: '#113CCF', seguro: true,
    tipo: 'iptv', url: 'https://streamer.metronethn.com/DisneyChannel/index.m3u8',
    desc: 'Disney Channel America Latina, ao vivo.' },
  { nome: 'KURIAKOS KIDS', programa: 'INFANTIL · 24/7', categoria: 'INFANTIL', cor: '#4CAF50', seguro: true,
    tipo: 'iptv', url: 'https://w2.manasat.com/kkids/smil:kkids.smil/playlist.m3u8',
    desc: 'Canal infantil ao vivo (1080p).' },
  { nome: 'NICK JR.', programa: 'INFANTIL · 24/7', categoria: 'INFANTIL', cor: '#FF6600', seguro: true,
    tipo: 'iptv', url: 'https://streamer.metronethn.com/NickJr/index.m3u8',
    desc: 'Nick Jr. America Latina, ao vivo (1080p).' },
  { nome: 'NICKTOONS', programa: 'DESENHOS · 24/7', categoria: 'INFANTIL', cor: '#FF8C00', seguro: true,
    tipo: 'iptv', url: 'https://stmv2.srvif.com/nicktoons/nicktoons/playlist.m3u8',
    desc: 'NickToons — animações da Nickelodeon, ao vivo.' },
  { nome: 'REINO INFANTIL', programa: 'DESENHOS · 24/7', categoria: 'INFANTIL', cor: '#FFC107', seguro: true,
    tipo: 'iptv', url: 'https://www.khuwemultimedia.com/hls/reinoinfantiltv/reinoinfantiltv.m3u8',
    desc: 'Animacao infantil em portugues, ao vivo.' },
  { nome: 'BOX KIDS', programa: 'DESENHOS · 24/7', categoria: 'INFANTIL', cor: '#F58220', seguro: false,
    tipo: 'iptv', url: 'http://45.190.28.50/BOX_KIDS_HD/index.m3u8',
    desc: 'Desenhos para a criançada, ao vivo.' },
  { nome: 'DISNEY JR.', programa: 'INFANTIL · 24/7', categoria: 'INFANTIL', cor: '#5B2D8E', seguro: false,
    tipo: 'iptv', url: 'http://177.234.249.178:8888/DISNEY-JR/index.m3u8',
    desc: 'Disney Junior America Latina, ao vivo (1080p).' },
  { nome: 'GLOOBINHO', programa: 'DESENHOS · 24/7', categoria: 'INFANTIL', cor: '#00AEEF', seguro: false,
    tipo: 'iptv', url: 'http://177.52.24.163/GLOOBINHO-HD/index.m3u8',
    desc: 'Programação infantil ao vivo.' },

  /* ── CLÁSSICOS ── */
  { nome: 'AWTV', programa: 'CLASSICOS · 24/7', categoria: 'CLÁSSICOS', cor: '#B08D57', seguro: true,
    tipo: 'iptv', url: 'https://awtv.nuvemplay.live/hls/stream.m3u8',
    desc: 'Series e filmes classicos, ao vivo (1080p).' },
  { nome: 'CLASSIQUE TV', programa: 'CINEMA CLASSICO', categoria: 'CLÁSSICOS', cor: '#8D6E63', seguro: true,
    tipo: 'iptv', url: 'https://stmv1.srvif.com/classique/classique/playlist.m3u8',
    desc: 'Cinema classico 24 horas.' },

  /* ── SÉRIES ── */
  { nome: 'TV SERIES', programa: 'SERIES · 24/7', categoria: 'SÉRIES', cor: '#5C6BC0', seguro: true,
    tipo: 'iptv', url: 'https://stmv1.srvif.com/tvserie/tvserie/playlist.m3u8',
    desc: 'Maratona de series, ao vivo.' },
  { nome: 'TVI FICCAO', programa: 'SERIES · 24/7', categoria: 'SÉRIES', cor: '#3949AB', seguro: true,
    tipo: 'iptv', url: 'https://raw.githubusercontent.com/thomraider12/canaistvpt/main/m3u8s/tvificcao.m3u8',
    desc: 'Ficcao portuguesa da TVI, ao vivo.' },
  { nome: 'TNT NOVELAS', programa: 'NOVELAS · 24/7', categoria: 'SÉRIES', cor: '#C8102E', seguro: false,
    tipo: 'iptv', url: 'http://190.93.224.42/TNT-NOVELAS/index.m3u8',
    desc: 'TNT Novelas ao vivo (1080p).' },

  /* ── CINEMA ── */
  { nome: 'AMC', programa: 'FILMES · 24/7', categoria: 'CINEMA', cor: '#000000', seguro: true,
    tipo: 'iptv', url: 'https://streamer.metronethn.com/AMC/index.m3u8',
    desc: 'AMC America Latina, ao vivo (1080p).' },
  { nome: 'CINDIE TV', programa: 'CINEMA INDIE', categoria: 'CINEMA', cor: '#7E57C2', seguro: true,
    tipo: 'iptv', url: 'https://cc-hqw8u5r1nshjc.akamaized.net/scheduler/scheduleMaster/352.m3u8',
    desc: 'Cinema independente, ao vivo (1080p).' },
  { nome: 'KURIAKOS CINE', programa: 'FILMES · 24/7', categoria: 'CINEMA', cor: '#4CAF50', seguro: true,
    tipo: 'iptv', url: 'https://w2.manasat.com/kcine/smil:kcine.smil/playlist.m3u8',
    desc: 'Filmes 24 horas (1080p).' },
  { nome: 'MOVIESPHERE', programa: 'FILMES · 24/7', categoria: 'CINEMA', cor: '#673AB7', seguro: true,
    tipo: 'iptv', url: 'https://amg00353-lionsgatefilmsi-moviesphereaus-samsungau-7qzhf.amagi.tv/playlist/amg00353-lionsgatefilmsi-moviesphereaus-samsungau/playlist.m3u8',
    desc: 'Canal FAST da Lionsgate, ao vivo.' },
  { nome: 'MYTIME MOVIES', programa: 'FILMES · 24/7', categoria: 'CINEMA', cor: '#5E35B1', seguro: true,
    tipo: 'iptv', url: 'https://appletree-mytime-samsungbrazil.amagi.tv/playlist.m3u8',
    desc: 'Canal FAST de filmes, ao vivo.' },
  { nome: 'AXN', programa: 'SERIES E FILMES', categoria: 'CINEMA', cor: '#1A1A1A', seguro: false,
    tipo: 'iptv', url: 'http://138.255.2.6:8084/AXN/index.m3u8',
    desc: 'AXN ao vivo (1080p).' },
  { nome: 'AXN MOVIES', programa: 'FILMES · 24/7', categoria: 'CINEMA', cor: '#2B2B2B', seguro: false,
    tipo: 'iptv', url: 'http://50.7.120.34:8080/AXN_BLACK/index.m3u8',
    desc: 'AXN Movies ao vivo.' },
  { nome: 'CINECANAL', programa: 'FILMES · 24/7', categoria: 'CINEMA', cor: '#E4002B', seguro: false,
    tipo: 'iptv', url: 'http://138.121.15.230:9002/CINECANAL/index.m3u8',
    desc: 'Cinecanal ao vivo (1080p).' },
  { nome: 'SONY MOVIES', programa: 'FILMES · 24/7', categoria: 'CINEMA', cor: '#0033A0', seguro: false,
    tipo: 'iptv', url: 'http://45.162.64.114/SONY_MOVIES/index.m3u8',
    desc: 'Sony Movies ao vivo.' },

  /* ── HUMOR ── */
  { nome: 'FORA TEDIO', programa: 'HUMOR · 24/7', categoria: 'HUMOR', cor: '#FF7043', seguro: true,
    tipo: 'iptv', url: 'https://stmv2.srvif.com/foratedio/foratedio/playlist.m3u8',
    desc: 'Humor e variedades, ao vivo.' },
  { nome: 'COMEDY CENTRAL', programa: 'HUMOR · 24/7', categoria: 'HUMOR', cor: '#F4A100', seguro: false,
    tipo: 'iptv', url: 'http://15.204.246.24:8080/ComedyCentralHD/index.m3u8',
    desc: 'Comedy Central America Latina, ao vivo (1080p).' },

  /* ── MÚSICA ── */
  { nome: 'KPOP TV', programa: 'CLIPES · 24/7', categoria: 'MÚSICA', cor: '#7A5CFF', seguro: true,
    tipo: 'iptv', url: 'https://giatv.bozztv.com/giatv/giatv-kpoptvplay/kpoptvplay/playlist.m3u8',
    desc: 'O canal do K-pop, ao vivo.' },
  { nome: 'LAMORE ROCK', programa: 'ROCK · 24/7', categoria: 'MÚSICA', cor: '#333333', seguro: true,
    tipo: 'iptv', url: 'https://a.cdni.live/rodrigo2364/rodrigo2364/playlist.m3u8',
    desc: 'Rock Show WebTV — rock e som pesado, ao vivo.' },
  { nome: 'MUZANGALA TV', programa: 'MUSICA · 24/7', categoria: 'MÚSICA', cor: '#F9A825', seguro: true,
    tipo: 'iptv', url: 'https://5cf4a2c2512a2.streamlock.net/tvmuzangala/tvmuzangala/playlist.m3u8',
    desc: 'Musica lusofona de Angola, ao vivo (1080p).' },
  { nome: 'RFPTV', programa: 'MUSICA · 24/7', categoria: 'MÚSICA', cor: '#EC407A', seguro: true,
    tipo: 'iptv', url: 'https://video03.logicahost.com.br/rfptv/rfptv/playlist.m3u8',
    desc: 'Musica portuguesa, ao vivo.' },
  { nome: 'TRACE BRASIL', programa: 'URBANO · 24/7', categoria: 'MÚSICA', cor: '#E4002B', seguro: true,
    tipo: 'iptv', url: 'https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg01131-tracetv-tracebrazuca-samsungbr/playlist.m3u8',
    desc: 'Hip hop, funk e cultura urbana brasileira, ao vivo.' },
  { nome: 'TRACE TOCA', programa: 'CLIPES · 24/7', categoria: 'MÚSICA', cor: '#00BFA5', seguro: true,
    tipo: 'iptv', url: 'https://channels.trace.plus/Traceprod/TOCA_hd/index.m3u8',
    desc: 'Clipes brasileiros da Trace, ao vivo (1080p).' },
  { nome: 'TRACE URBAN', programa: 'URBANO · 24/7', categoria: 'MÚSICA', cor: '#FF4081', seguro: true,
    tipo: 'iptv', url: 'https://channels.trace.plus/Traceprod/URBAN_AFRIC_FR_hd/index.m3u8',
    desc: 'Hip hop e RnB internacional, ao vivo (1080p).' },
  { nome: 'TV CIDADE', programa: 'MUSICA · 24/7', categoria: 'MÚSICA', cor: '#26A69A', seguro: true,
    tipo: 'iptv', url: 'https://stmv1.srvif.com/tvcidade/tvcidade/playlist.m3u8',
    desc: 'Musica e cultura de Cabo Verde, ao vivo.' },
  { nome: 'MUSIC BOX', programa: 'CLIPES · 24/7', categoria: 'MÚSICA', cor: '#FF2D95', seguro: false,
    tipo: 'iptv', url: 'http://45.190.28.50/MUSIC_BOX_HD/index.m3u8',
    desc: 'Clipe nacional e internacional, ao vivo.' },

  /* ── TV ABERTA ── */
  { nome: 'BAND', programa: 'AO VIVO', categoria: 'TV ABERTA', cor: '#E4002B', seguro: true,
    tipo: 'iptv', url: 'https://media.cdntvms.com.br/band_sat/index.m3u8',
    desc: 'A Band ao vivo.' },
  { nome: 'CANAL UOL', programa: 'JORNALISMO · 24/7', categoria: 'TV ABERTA', cor: '#F5A623', seguro: true,
    tipo: 'iptv', url: 'https://video24.mais.uol.com.br/live/6146.m3u8',
    desc: 'Canal UOL, jornalismo e entrevistas ao vivo.' },
  { nome: 'COM BRASIL', programa: 'AO VIVO', categoria: 'TV ABERTA', cor: '#1B7F4E', seguro: true,
    tipo: 'iptv', url: 'https://br5093.streamingdevideo.com.br/abc/abc/playlist.m3u8',
    desc: 'COM Brasil ao vivo (1080p).' },
  { nome: 'CULTURA PARA', programa: 'AO VIVO', categoria: 'TV ABERTA', cor: '#00AEEF', seguro: true,
    tipo: 'iptv', url: 'https://player-tvcultura.stream.uol.com.br/live/tvcultura.m3u8',
    desc: 'TV Cultura ao vivo (sinal via UOL).' },
  { nome: 'RECORD', programa: 'AO VIVO', categoria: 'TV ABERTA', cor: '#C4170C', seguro: true,
    tipo: 'iptv', url: 'https://media.cdntvms.com.br/record_nacional_sat/index.m3u8',
    desc: 'Record nacional ao vivo.' },
  { nome: 'RECORD NEWS', programa: 'JORNALISMO · 24/7', categoria: 'TV ABERTA', cor: '#C4170C', seguro: true,
    tipo: 'iptv', url: 'https://5cf4a2c2512a2.streamlock.net/8016/8016/playlist.m3u8',
    desc: 'Record News — jornalismo 24 horas ao vivo.' },
  { nome: 'REDE BRASIL', programa: 'AO VIVO', categoria: 'TV ABERTA', cor: '#C4170C', seguro: true,
    tipo: 'iptv', url: 'https://redebrasil.nuvemplay.live/hls/stream.m3u8',
    desc: 'Rede Brasil ao vivo (1080p).' },
  { nome: 'REDE NGT', programa: 'AO VIVO', categoria: 'TV ABERTA', cor: '#0B3C8C', seguro: true,
    tipo: 'iptv', url: 'https://isaocorp.cloudecast.com/ngt/index.m3u8',
    desc: 'Rede NGT ao vivo (1080p).' },
  { nome: 'REDETV!', programa: 'AO VIVO', categoria: 'TV ABERTA', cor: '#2E2E2E', seguro: true,
    tipo: 'iptv', url: 'https://tv01.zas.media:1936/redetvparana/redetvparana/playlist.m3u8',
    desc: 'RedeTV! ao vivo (praca Parana, 1080p).' },
  { nome: 'SBT NEWS', programa: 'JORNALISMO · 24/7', categoria: 'TV ABERTA', cor: '#E30613', seguro: true,
    tipo: 'iptv', url: 'https://dai.google.com/linear/hls/event/1XSOdtQ0SH2G8OEmEfGgjQ/master.m3u8',
    desc: 'SBT News, jornalismo ao vivo.' },
  { nome: 'TV CULTURA', programa: 'AO VIVO', categoria: 'TV ABERTA', cor: '#00AEEF', seguro: true,
    tipo: 'iptv', url: 'https://fpa-gateway.tvcultura.com.br:8181/memfs/606caef0-a290-413d-9f1f-8fcdb3a73831.m3u8',
    desc: 'Cultura Fast — canal oficial da TV Cultura, ao vivo.' },
  { nome: 'TVE RS', programa: 'AO VIVO', categoria: 'TV ABERTA', cor: '#0093D5', seguro: true,
    tipo: 'iptv', url: 'https://streaming.procergs.com.br:8443/tve/stve/playlist.m3u8',
    desc: 'TV Educativa do Rio Grande do Sul (1080p).' },
  { nome: 'ARTE 1', programa: 'CULTURA · 24/7', categoria: 'TV ABERTA', cor: '#7B1FA2', seguro: false,
    tipo: 'iptv', url: 'http://45.162.64.114/ARTE1/index.m3u8',
    desc: 'Arte 1, cultura e documentarios ao vivo.' },
  { nome: 'GLOBONEWS', programa: 'JORNALISMO · 24/7', categoria: 'TV ABERTA', cor: '#0F52BA', seguro: false,
    tipo: 'iptv', url: 'http://177.52.24.163/GLOBO-NEWS-HD/index.m3u8',
    desc: 'GloboNews, jornalismo 24 horas ao vivo.' }
];
