/* ═══════════════════════════════════════════════════════════
   RETROVERSE — ESTACOES DA RADIO (fonte unica)
   59 estacoes, servidas por streams publicos.
   Nada e hospedado aqui.

   As estacoes de GTA vem do gtaradio.net, que retransmite as
   radios dos jogos. As demais vem da base Radio Browser.

   Todas verificadas em 17/08/2026: Content-Type de audio +
   bytes reais chegando, em 3 rodadas com intervalo (3/3).
   Todas em HTTPS — obrigatorio, senao o navegador bloqueia
   por mixed content na pagina publicada.

   Formato: { nome, categoria, cor, url, desc }
   ═══════════════════════════════════════════════════════════ */
window.RV_RADIOS = [

  /* ── GTA VICE CITY ── */
  { nome: 'EMOTION 98.3', categoria: 'GTA VICE CITY', cor: '#ff4fa3',
    url: 'https://audio.gtaradio.net/vc/emotion',
    desc: 'Baladas romanticas de Vice City' },
  { nome: 'FEVER 105', categoria: 'GTA VICE CITY', cor: '#ff4fa3',
    url: 'https://audio.gtaradio.net/vc/fever',
    desc: 'Disco e funk de Vice City' },
  { nome: 'KCHAT', categoria: 'GTA VICE CITY', cor: '#ff4fa3',
    url: 'https://audio.gtaradio.net/vc/kchat',
    desc: 'Talk show de Vice City' },
  { nome: 'V-ROCK', categoria: 'GTA VICE CITY', cor: '#ff4fa3',
    url: 'https://audio.gtaradio.net/vc/vrock',
    desc: 'Hard rock e metal de Vice City' },
  { nome: 'VCPR', categoria: 'GTA VICE CITY', cor: '#ff4fa3',
    url: 'https://audio.gtaradio.net/vc/vcpr',
    desc: 'Radio falada de Vice City' },
  { nome: 'WAVE 103', categoria: 'GTA VICE CITY', cor: '#ff4fa3',
    url: 'https://audio.gtaradio.net/vc/wave',
    desc: 'New wave e synthpop de Vice City' },

  /* ── GTA SAN ANDREAS ── */
  { nome: 'CSR 103.9', categoria: 'GTA SAN ANDREAS', cor: '#c8a02a',
    url: 'https://audio.gtaradio.net/sa/csr',
    desc: 'Soul e RnB contemporaneo' },
  { nome: 'SF-UR', categoria: 'GTA SAN ANDREAS', cor: '#c8a02a',
    url: 'https://audio.gtaradio.net/sa/sfur',
    desc: 'House de San Fierro' },
  { nome: 'WCTR', categoria: 'GTA SAN ANDREAS', cor: '#c8a02a',
    url: 'https://audio.gtaradio.net/sa/wctr',
    desc: 'Radio falada de San Andreas' },

  /* ── GTA III ── */
  { nome: 'GAME RADIO', categoria: 'GTA III', cor: '#8fa3b8',
    url: 'https://audio.gtaradio.net/3/game',
    desc: 'Hip hop de Liberty City' },
  { nome: 'HEAD RADIO', categoria: 'GTA III', cor: '#8fa3b8',
    url: 'https://audio.gtaradio.net/3/head',
    desc: 'Pop rock de Liberty City' },
  { nome: 'LIPS 106', categoria: 'GTA III', cor: '#8fa3b8',
    url: 'https://audio.gtaradio.net/3/lips',
    desc: 'Pop de Liberty City' },
  { nome: 'MSX FM', categoria: 'GTA III', cor: '#8fa3b8',
    url: 'https://audio.gtaradio.net/3/msx',
    desc: 'Drum and bass de Liberty City' },
  { nome: 'RISE FM', categoria: 'GTA III', cor: '#8fa3b8',
    url: 'https://audio.gtaradio.net/3/rise',
    desc: 'Trance de Liberty City' },

  /* ── GTA IV ── */
  { nome: 'FUSION FM', categoria: 'GTA IV', cor: '#e0703a',
    url: 'https://audio.gtaradio.net/4/fusion_fm',
    desc: 'Jazz fusion de Liberty City' },
  { nome: 'INT. FUNK 99', categoria: 'GTA IV', cor: '#e0703a',
    url: 'https://audio.gtaradio.net/4/afro_beat',
    desc: 'Funk internacional de Liberty City' },
  { nome: 'JAZZ NATION', categoria: 'GTA IV', cor: '#e0703a',
    url: 'https://audio.gtaradio.net/4/jazz_nation',
    desc: 'Jazz de Liberty City' },
  { nome: 'LIBERTY ROCK', categoria: 'GTA IV', cor: '#e0703a',
    url: 'https://audio.gtaradio.net/4/liberty_rock',
    desc: 'Rock classico de Liberty City' },
  { nome: 'VLADIVOSTOK FM', categoria: 'GTA IV', cor: '#e0703a',
    url: 'https://audio.gtaradio.net/4/vladivostok',
    desc: 'Musica do leste europeu' },

  /* ── RETRO GAMING ── */
  { nome: 'FLASH FM', categoria: 'RETRO GAMING', cor: '#00ff41',
    url: 'https://audio.gtaradio.net/vc/flash',
    desc: 'A radio dentro do jogo' },
  { nome: 'GAME BYTES', categoria: 'RETRO GAMING', cor: '#00ff41',
    url: 'https://broadcast.shoutcheap.com/proxy/gbrgameb/stream',
    desc: 'Trilhas de video game sem parar' },
  { nome: 'GAMEPAD', categoria: 'RETRO GAMING', cor: '#00ff41',
    url: 'https://centova.listenon.in/proxy/gamepad/stream',
    desc: 'Trilhas classicas de console' },
  { nome: 'GAMESBORO', categoria: 'RETRO GAMING', cor: '#00ff41',
    url: 'https://radio.gamesboro.org/listen/gamesboro_radio/radio.mp3',
    desc: 'Nintendo, PlayStation e Sega' },
  { nome: 'PIXEL PIANO', categoria: 'RETRO GAMING', cor: '#00ff41',
    url: 'https://pixelplot.stream.publicradio.org/pixelplot.mp3',
    desc: 'Trilhas de jogos em piano' },
  { nome: 'RADIOSEGA', categoria: 'RETRO GAMING', cor: '#00ff41',
    url: 'https://icecast.radiosega.net/live',
    desc: 'Trilhas de Mega Drive, Saturn e Dreamcast' },
  { nome: 'RAINWAVE', categoria: 'RETRO GAMING', cor: '#00ff41',
    url: 'https://relay.rainwave.cc/game.ogg',
    desc: 'Trilhas votadas pelos ouvintes' },
  { nome: 'RETROBYTE', categoria: 'RETRO GAMING', cor: '#00ff41',
    url: 'https://retrobytesradio.radioca.st/stream',
    desc: 'Trilhas retro em alta qualidade' },
  { nome: 'SHOOT EM UP', categoria: 'RETRO GAMING', cor: '#00ff41',
    url: 'https://stream.shmupradio.com/320',
    desc: 'Trilhas de shmups e arcades' },
  { nome: 'SONIC RADIO', categoria: 'RETRO GAMING', cor: '#00ff41',
    url: 'https://play.soundtest.fm/sonic',
    desc: 'Dedicada ao ourico azul' },

  /* ── CHIPTUNE ── */
  { nome: 'CHIPTUNE 24/7', categoria: 'CHIPTUNE', cor: '#7A5CFF',
    url: 'https://radio.zelerk.com/listen/chiptune/stream.mp3',
    desc: 'Chiptune sem parar' },
  { nome: 'CPC SCENE', categoria: 'CHIPTUNE', cor: '#7A5CFF',
    url: 'https://a1.asurahosting.com/listen/cpc_scene_radio/radio.mp3',
    desc: 'Cena do Amstrad CPC' },
  { nome: 'KEYGEN FM', categoria: 'CHIPTUNE', cor: '#7A5CFF',
    url: 'https://keygen-fm.kodatek.app/listen/keygen-fm/radio.mp3',
    desc: 'Chiptune da era dos keygens' },
  { nome: 'KOHINA', categoria: 'CHIPTUNE', cor: '#7A5CFF',
    url: 'https://kohina.duckdns.org/icecast/stream.ogg',
    desc: 'Chiptune e musica de tracker' },
  { nome: 'NOLIFE', categoria: 'CHIPTUNE', cor: '#7A5CFF',
    url: 'https://listen.nolife-radio.com/',
    desc: 'Chiptune e trilhas de jogos' },
  { nome: 'PUNGAS', categoria: 'CHIPTUNE', cor: '#7A5CFF',
    url: 'https://pungasradio.rebel.ar/pungasradio',
    desc: 'Arcade, chiptune e demoscene' },
  { nome: 'QUANTUM', categoria: 'CHIPTUNE', cor: '#7A5CFF',
    url: 'https://radio.erb.pw/listen/subspace/radio.mp3',
    desc: 'Arcade e demoscene' },
  { nome: 'RED ROBOT', categoria: 'CHIPTUNE', cor: '#7A5CFF',
    url: 'https://asteroid.asgardius.company/listen/r3/live',
    desc: 'Chiptune espacial e eletronico' },
  { nome: 'RETRO PLUM', categoria: 'CHIPTUNE', cor: '#7A5CFF',
    url: 'https://s85.radiolize.com/radio/8090/radio.mp3',
    desc: 'Amiga, Atari, C64 e demoscene' },

  /* ── SYNTHWAVE ── */
  { nome: 'DATAWAVE', categoria: 'SYNTHWAVE', cor: '#b14fff',
    url: 'https://stream.nightride.fm/datawave.mp3',
    desc: 'Synthwave sombrio e cyberpunk' },
  { nome: 'NIGHT DRIVE', categoria: 'SYNTHWAVE', cor: '#b14fff',
    url: 'https://a5.asurahosting.com:7920/radio.mp3',
    desc: 'Synthwave e retrowave de estrada' },
  { nome: 'NIGHTRIDE FM', categoria: 'SYNTHWAVE', cor: '#b14fff',
    url: 'https://stream.nightride.fm/nightride.mp3',
    desc: 'Synthwave para dirigir a noite' },
  { nome: 'NIGHTWAVE PLAZA', categoria: 'SYNTHWAVE', cor: '#b14fff',
    url: 'https://radio.plaza.one/mp3',
    desc: 'Vaporwave e mall music dos anos 90' },
  { nome: 'YUMI CO.', categoria: 'SYNTHWAVE', cor: '#b14fff',
    url: 'https://yumicoradio.net/stream',
    desc: 'Citypop e future funk japones' },

  /* ── EUROBEAT ── */
  { nome: 'ITALO DANCE 90s', categoria: 'EUROBEAT', cor: '#00d4ff',
    url: 'https://mscp2.live-streams.nl:8152/italodance',
    desc: 'Italo dance dos anos 90, clima de Initial D' },
  { nome: 'NFS.ONL RADIO', categoria: 'EUROBEAT', cor: '#00d4ff',
    url: 'https://radio.nfs.onl:8443/stream.ogg',
    desc: 'Radio da comunidade Need for Speed' },
  { nome: 'RMI EURO DISCO', categoria: 'EUROBEAT', cor: '#00d4ff',
    url: 'https://ams-pioneer02.dedicateware.com:2655/stream',
    desc: 'Euro disco e dance' },

  /* ── ANIME ── */
  { nome: 'JAPAN RADIO', categoria: 'ANIME', cor: '#FF2D95',
    url: 'https://stream.japanradio.de/live',
    desc: 'J-pop, J-rock e eurobeat' },
  { nome: 'RADIO ANIMU', categoria: 'ANIME', cor: '#FF2D95',
    url: 'https://stream.animu.moe/320',
    desc: 'Musica de anime em alta qualidade' },
  { nome: 'STEREO ANIME', categoria: 'ANIME', cor: '#FF2D95',
    url: 'https://radio.stereoanime.com/listen/stereoanime/128',
    desc: 'Aberturas e encerramentos de anime' },

  /* ── BRASIL ── */
  { nome: '98 ROCK', categoria: 'BRASIL', cor: '#00AEEF',
    url: 'https://8185.brasilstream.com.br/stream',
    desc: 'Rock nacional e internacional' },
  { nome: 'BANDNEWS', categoria: 'BRASIL', cor: '#00AEEF',
    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/BANDNEWSFM_BHAAC.aac',
    desc: 'Jornalismo 24 horas' },
  { nome: 'FLASHBACK', categoria: 'BRASIL', cor: '#00AEEF',
    url: 'https://stm4.voxhd.com.br:7086/;',
    desc: 'Sucessos das antigas' },
  { nome: 'JOVEM PAN', categoria: 'BRASIL', cor: '#00AEEF',
    url: 'https://8062.brasilstream.com.br/mp3',
    desc: 'Jovem Pan ao vivo' },
  { nome: 'MIX FM', categoria: 'BRASIL', cor: '#00AEEF',
    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/MIXFM_SAOPAULOAAC.aac?dist=mix-web-player-radio-ao-vivo&934992.6600449783',
    desc: 'Pop e hits, ao vivo' },
  { nome: 'MPB', categoria: 'BRASIL', cor: '#00AEEF',
    url: 'https://ice.fabricahost.com.br/metropolitanampb',
    desc: 'O melhor da MPB' },
  { nome: 'RADIO USP', categoria: 'BRASIL', cor: '#00AEEF',
    url: 'https://flow.emm.usp.br:8008/radiousp-128.mp3',
    desc: 'Cultura e musica da USP' },
  { nome: 'ROCK 89 FM', categoria: 'BRASIL', cor: '#00AEEF',
    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_89FM_ADP.aac?dist=site-89fm',
    desc: 'A radio rock, ao vivo' },
  { nome: 'SAMBA FM', categoria: 'BRASIL', cor: '#00AEEF',
    url: 'https://hts01.brascast.com:8428/stream',
    desc: 'Samba e pagode, ao vivo' },
  { nome: 'SMOOTH JAZZ', categoria: 'BRASIL', cor: '#00AEEF',
    url: 'https://sc4s.cdn.upx.com:8176/stream',
    desc: 'Jazz suave, ao vivo' }
];
